### PR TITLE
Write auto column width

### LINKED ISSUE #682: Auto adjust column width for excel writing
### Excel Type

- [x] XLSX
- [x] XLSM
- [ ] CSV
- [ ] OTHER

I have been looking into implementing an autosize feature in a similar fashion as dimensions are handled in fastmode.

Fastmode changes the filemode of the zipfile to support seeking. Is there a reason why this is not the default? Is it slower?

The autosize feature would require fastmode to be enabled. So I want to remove the fastmode option and make it the default behaviour if you have no objections @shps951023

### PR DESCRIPTION
**Pull request by Discolai**
Closes #682

This PR implements writing excel documents with auto column width. The required width is an estimate based on the string length and an average factor based on the Calibri font with size 11pt.

### CODE REVIEW

**Review by shps951023 — APPROVED** [review]

**Comment by shps951023** [comment]
❤ Reviewed & Merged, please feel free to feedback

**Comment by stian-bay** [comment]
Could this also check the header column width? The header can be longer than the data. Im setting the header name in the data model like this ` [ExcelColumn(Name = "My longer column header", Index = 0)]`

**Comment by michelebastione** [comment]
Resolved #379

**Comment by Narendin** [comment]
@stian-bay try this

```
List<Dictionary<string, object>> data; // data to export

var headers = data.SelectMany(x => x.Keys).Distinct().Select(x => new DynamicExcelColumn(x)
{
    Width = ExcelWidthCollection.GetApproximateRequiredCalibriWidth(x.Length)
}).ToArray();

var config = new OpenXmlConfiguration
{
    EnableAutoWidth = true,
    FastMode = true,
    DynamicColumns = headers
};

MiniExcel.SaveAs(path, data, configuration: config);
```

**Comment by stian-bay** [comment]
> @stian-bay try this
> 
> 
> 
> ```
> 
> List<Dictionary<string, object>> data; // data to export
> 
> 
> 
> var headers = data.SelectMany(x => x.Keys).Distinct().Select(x => new DynamicExcelColumn(x)
> 
> {
> 
>     Width = ExcelWidthCollection.GetApproximateRequiredCalibriWidth(x.Length)
> 
> }).ToArray();
> 
> 
> 
> var config = new OpenXmlConfiguration
> 
> {
> 
>     EnableAutoWidth = true,
> 
>     FastMode = true,
> 
>     DynamicColumns = headers
> 
> };
> 
> 
> 
> MiniExcel.SaveAs(path, data, configuration: config);
> 
> ```
> 
> 

Ah cool, I will try this. Thanks

**Comment by stian-bay** [comment]
Got it working in my dynamic method like this. Maybe a little more complex, but this seems to be working great 🎉

```
public static MemoryStream Export<T>(IEnumerable<T> data)
{
    var columns = typeof(T)
        .GetProperties()
        .Select(p => new { Property = p, Attribute = p.GetCustomAttribute<ExcelColumnAttribute>() })
        .Select(x => new DynamicExcelColumn(x.Property.Name)
        {
            Name = x.Attribute?.Name,
            Width = ExcelWidthCollection.GetApproximateTextWidth(x.Attribute?.Name?.Length ?? x.Property.Name.Length) + 1
        })
        .ToArray();

    var config = ExportSettings.DefaultConfiguration;

    config.DynamicColumns = columns;

    var memoryStream = new MemoryStream();
    memoryStream.SaveAs(data, configuration: config);
    memoryStream.Seek(0, SeekOrigin.Begin);

    return memoryStream;
}
```

**Pull request merged**
