### PR TITLE
add support for grouped cells

### PR DESCRIPTION
**Pull request by eynarhaji**
I had a request to fill data not line by line, but multiple lines at once. So I introduced new keyword @group to reach that purpose. If lines are between @group and @endgroup tags, they will be repeated together. Moreover, @header tag helps user to cancel repeating same header rows for each group.

### CODE REVIEW

**Comment by eynarhaji** [comment]
With @group  tag and with @header tag

Before
before_with_header

After
after_with_header

**Comment by eynarhaji** [comment]
With @group tag and without @header tag

Before
before_without_header

After
after_without_header

**Comment by eynarhaji** [comment]
Without @group tag

Before
without_group

After
without_group_after

**Review by shps951023 — COMMENTED** [review]
@eynarhaji it's awesome 👍👍

**Comment by eynarhaji** [comment]
@shps951023 accepted

**Comment by abou-emish** [comment]
It works great with one group, but not with multiple ones in the same excel sheet.

**Comment by eynarhaji** [comment]
@abou-emish Hi there, please share sample worksheet to fix it.

**Comment by abou-emish** [comment]
Hello @eynarhaji 
[ApplicationTemplateSample.xlsx](https://github.com/mini-software/MiniExcel/files/10902245/ApplicationTemplateSample.xlsx)

Provide more than one object in the second group array, you will find the following issues

1. First object is ignored
2. @group, @header rows are cleared but not deleted/replaced

**Comment by abou-emish** [comment]
There is another issue, when there is a row inside the group with text only "no {{template}}", it causes Object reference not set to an instance exception

**Comment by eynarhaji** [comment]
@abou-emish yes this issue is detected by me. Fixing that also.

**Comment by abou-emish** [comment]
@eynarhaji Thanks a lot for your efforts, can you please give me a rough estimate when this fix will be available?

**Comment by eynarhaji** [comment]
@abou-emish end of this week

**Comment by abou-emish** [comment]
Hello @eynarhaji , I hope you are doing fine.
Do we have a good progress ?

**Pull request merged**
