### PR TITLE
Custom DateTime format

### PR DESCRIPTION
**Pull request by DancePanda42**
Allows the user to define a user-defined date format, whereby the date information is not lost.

this will be fix also the issue #424 

sorry but I also had to remove the `goto` 😄

### CODE REVIEW

**Comment by jiaguangli** [comment]
thanks for your pull request,
i have replied issure #424,
Do we really need this feature?
We should discuss this seriously.

**Comment by DancePanda42** [comment]
Hi,
For me, the main reason for this feature is that it makes it easier to use the filter for a date in Excel.
Which unfortunately is not the case if the date is a string.

**Comment by jiaguangli** [comment]
> Hi, For me, the main reason for this feature is that it makes it easier to use the filter for a date in Excel. Which unfortunately is not the case if the date is a string. Maybe I didn't understand the issue correctly. I thought that would pursue the same goal.

No, you are correct, but we have to consider whether this approach makes sense and whether it will cause trouble in the future.
It's really hard to decide.

**Comment by jiaguangli** [comment]
image
image
image

`Format = "dd.mm.yyyy hh:mm:ss"`
doesn't actually work for excel，Maybe this is not the result we want.

**Comment by DancePanda42** [comment]
image
image

It was never my intention to change the default date format to `dd.mm.yyyy hh:mm:ss`.
My PR rather referred to the comment [// TODO: now it'll lose date type information](https://github.com/mini-software/MiniExcel/blob/12bb1c0028530de1034bf16fd5458e9aad1ea4eb/src/MiniExcel/OpenXml/ExcelOpenXmlSheetWriter.DefaultOpenXml.cs#L343).
As a result, nothing should change for the users, except that the date information will now be available in Excel.
Of course, if users have been further processing the string within the Excel table, this would be a breaking change since it is now a DateOA double instead of a string.

**Comment by jiaguangli** [comment]
I understood what you meant before.
Can `SaveAsync` also be supported？
And `GenerateSheetByIDataReader` thanks,

**Comment by DancePanda42** [comment]
Hi, yes no problem.
I think the reference to the issue took things in the wrong direction.

Support for async should not be a big effort anymore.
The support for `GenerateSheetByIDataReader` is already provided.
[DynamicColumnsConfigurationIsUsedWhenCreatingExcelUsingIDataReader](https://github.com/mini-software/MiniExcel/blob/4b6d0537198f35696309f6a7e70478da7fe428c3/tests/MiniExcelTests/MiniExcelOpenXmlTests.cs#L1217)

Additionally, I was considering implementing the support for the templates as well. For that, I will open a new PR when the time comes.

**Review by jiaguangli — APPROVED** [review]
good idea

**Review by jiaguangli — APPROVED** [review]

**Review by jiaguangli — APPROVED** [review]

**Comment by jiaguangli** [comment]
> Hi, yes no problem. I think the reference to the issue took things in the wrong direction.
> 
> Support for async should not be a big effort anymore. The support for `GenerateSheetByIDataReader` is already provided. [DynamicColumnsConfigurationIsUsedWhenCreatingExcelUsingIDataReader](https://github.com/mini-software/MiniExcel/blob/4b6d0537198f35696309f6a7e70478da7fe428c3/tests/MiniExcelTests/MiniExcelOpenXmlTests.cs#L1217)
> 
> Additionally, I was considering implementing the support for the templates as well. For that, I will open a new PR when the time comes.

Hi,please sign your commits

**Review by shps951023 — APPROVED** [review]

**Comment by shps951023** [comment]
👍👍👍
@DancePanda42  Could we invite you to our team?

**Pull request merged**
